# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

url: http://kaiw.github.com
title: Ambivalent Certainty
subtitle: One of these options <em>must</em> be correct
author: Kai Willadsen
simple_search: https://google.com/search
description:

github_username:  kaiw

gems: [jekyll-watch, jekyll-paginate, rouge]

paginate: 5
highlighter: rouge
